import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

test('pfn cover artwork generator reproduces the bundled SVG', () => {
  const outDir = fs.mkdtempSync(path.join(os.tmpdir(), 'pfpdf-cover-art-'));
  try {
    execFileSync(process.execPath, [path.join(root, 'scripts', 'generate-pfn-cover-art.mjs'), '--preview', outDir], { stdio: 'ignore' });
    const generated = fs.readFileSync(path.join(outDir, 'wovenAiryCanopy.svg'));
    const bundled = fs.readFileSync(path.join(root, 'resources', 'templates', 'pfn', 'cover-art.svg'));
    assert.deepEqual(generated, bundled);
    const artwork = bundled.toString();
    assert.match(artwork, /generated by scripts\/generate-pfn-cover-art\.mjs \(variant: wovenAiryCanopy\)/);
    assert.match(artwork, /stop-color="#111b64"[^]*stop-color="#19438f"[^]*stop-color="#1b75b4"/);
    assert.match(artwork, /preserveAspectRatio="xMidYMid slice"/);
  } finally {
    fs.rmSync(outDir, { recursive: true, force: true });
  }
});
